### ISSUE TITLE
Api token becomes exposed to public

### ISSUE THREAD

**Issue by huynq2007** [fredrikburman/shopify-flask-backend#1]
Hello,

I have read your blog post [here](https://www.tigersandtacos.dev/posts/create-a-shopify-backend-service-in-python-flask/). Nice write up!
(I'm new to Shopify development, so your boilerplate is pretty awesome tool)

BTW, I noticed that the Api token is being saved in template file which is exposed to the user. He can use that token to call directly to your backend Api which is  probably an issue to consider. 
https://github.com/fredrikburman/shopify-flask-backend/blob/main/app_shopify/templates/index.html#L22

**Comment by fredrikburman** [comment]
Hey, happy to hear that the boilerplate is helping you!
And also thanks for raising your concern about the API token, you should always be mindful whenever you see API tokens in a template, in this case we need to consider; when is this template being rendered.

The way it works today is that we get a request from Shopify, we verify that the request is coming from Shopify using the [HMAC](https://shopify.dev/apps/auth/oauth#verification): 

https://github.com/fredrikburman/shopify-flask-backend/blob/06f2fd9a798929a7a5075277f4fb50a788f84894/app_shopify/views.py#L127

Since the query string is validated that it's coming from Shopify we use the shop query parameter to pick up the API token from the merchant profile in our database and add it to the page. 
Then we add it to the template so that we can use that key to make authenticated requests to the backend service, for example updating the profile or any other cool stuff you want to do.

Hope that clear things up a bit.

**Comment by huynq2007** [comment]
even if someone has uninstalled the application already, he can still use the token to call directly to the backend API from an app outside Shopify.
I'm concerned about the API backend, is it necessary to check if the token is only valid for his merchant profile?

```
@shopify_bp.route('/demo-post-request', methods=['POST'])
@token_auth.login_required
def demo_post_request():
  # before we can do update something here, do we need to validate the token is only valid for our own store?
```

**Comment by fredrikburman** [comment]
Sorry for the delayed response, had to do family things yesterday.

You are correct, that is an issue which I have fixed. Checkout this commit: https://github.com/fredrikburman/shopify-flask-backend/commit/282076824109b8bd3618063c3c687464c25f4953

**Comment by huynq2007** [comment]
nice!
